<a href="https://colab.research.google.com/github/imend35/verianalizokulu-yapayzeka-python/blob/main/NumPy_Y%C3%BCksek_Performansl%C4%B1_Diziler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Harika\! Veri Bilimine yolculuğumuzun ilk adımı olan **NumPy (Numerical Python)** ile başlıyoruz.

NumPy, Python'da bilimsel hesaplamalar için temel kütüphanedir. Özellikle **büyük, çok boyutlu diziler (arrays)** ve bu diziler üzerinde yüksek performanslı matematiksel işlemler yapma yeteneği sayesinde veri analizi ve makine öğreniminin vazgeçilmezidir.

-----

## 9\. NumPy: Yüksek Performanslı Diziler

### 9.1. NumPy Dizileri (`ndarray`)

Python'daki standart listelerin aksine, NumPy'nin temel veri yapısı olan **`ndarray`** (N-Dimensional Array), aynı türden verileri (genellikle sayılar) bitişik hafıza bloklarında saklar. Bu, işlemleri *çok daha hızlı* yapmasını sağlar.

#### 💡 Kütüphaneyi İçe Aktarma

NumPy genellikle standart olarak `np` takma adıyla (alias) içe aktarılır:

```python
import numpy as np
```

#### Dizi Oluşturma

Bir Python listesini kolayca NumPy dizisine dönüştürebilirsiniz:

```python
# Standart Python listesi
python_listesi = [1, 2, 3, 4, 5]

# NumPy Dizisi (Tek Boyutlu)
numpy_dizi = np.array(python_listesi)
print(numpy_dizi) # Çıktı: [1 2 3 4 5]

# Çok Boyutlu Dizi (Matris) Oluşturma (2x3)
matris = np.array([[10, 20, 30], [40, 50, 60]])
print(matris)
# Çıktı:
# [[10 20 30]
#  [40 50 60]]
```

#### Hazır Fonksiyonlarla Dizi Oluşturma

NumPy, dizileri hızla oluşturmak için kullanışlı fonksiyonlar sunar:

| Fonksiyon | Amaç | Örnek |
| :--- | :--- | :--- |
| **`np.zeros(boyut)`** | Tamamen sıfırlardan oluşan dizi. | `np.zeros(3)` $\rightarrow$ `[0. 0. 0.]` |
| **`np.ones(boyut)`** | Tamamen birlerden oluşan dizi. | `np.ones((2, 2))` $\rightarrow$ `[[1. 1.], [1. 1.]]` |
| **`np.arange(start, stop)`** | Belirtilen aralıkta sayı dizisi. | `np.arange(5)` $\rightarrow$ `[0 1 2 3 4]` |

### 9.2. Dizilerin Özellikleri

Bir `ndarray` nesnesinin boyutunu, şeklini ve veri tipini kontrol edebiliriz:

| Özellik | Amaç | Örnek |
| :--- | :--- | :--- |
| **`.ndim`** | Dizinin boyut sayısı (eksen sayısı). | 2x3 matris için $\rightarrow$ `2` |
| **`.shape`** | Dizinin her boyuttaki eleman sayısı (tuple). | 2x3 matris için $\rightarrow$ `(2, 3)` |
| **`.dtype`** | Dizideki elemanların veri tipi. | `int64` veya `float64` gibi. |

### 9.3. Vektörize İşlemler (Hızın Sırrı)

NumPy'nin en büyük avantajı, tüm diziler üzerinde aynı anda işlem yapabilme yeteneğidir. Buna **Vektörizasyon** denir. Standart Python listelerinde her elemanı döngüyle gezmek gerekirken, NumPy'de aritmetik operatörler doğrudan tüm diziye uygulanır.

```python
dizi_a = np.array([1, 2, 3])
dizi_b = np.array([10, 20, 30])

# Vektörize Toplama (Eleman elemana toplama)
toplam = dizi_a + dizi_b
print(toplam) # Çıktı: [11 22 33]

# Skaler Çarpma (Her elemanı 2 ile çarp)
carpim = dizi_a * 2
print(carpim) # Çıktı: [2 4 6]

# Karşılaştırma (Boolean dizi döndürür)
buyuk_mu = dizi_a > 1
print(buyuk_mu) # Çıktı: [False  True  True]
```

-----

## 📝 Alıştırma: NumPy Dizileri

1.  **Dizi Oluşturma:**
      * `sıfırlar` adında, `3` satır ve `2` sütundan oluşan, tamamı sıfır olan bir matris (`np.zeros`) oluşturun.
      * `aralık` adında, 10'dan başlayıp 50'ye kadar (50 dahil değil) 5'er 5'er artan bir dizi (`np.arange`) oluşturun.
2.  **Özellikleri Kontrol Etme:**
      * `matris = np.array([[1, 2], [3, 4]])` dizisinin `.shape` ve `.ndim` özelliklerini ekrana yazdırın.
3.  **Vektörize İşlem:**
      * `dizi = np.array([5, 10, 15, 20])` dizisindeki tüm elemanların karekökünü `np.sqrt()` fonksiyonunu kullanarak alın ve sonucu `karekokler` değişkenine atayıp yazdırın.

NumPy'nin gücünü hissetmeye başladınız mı? Bu alıştırmaları tamamladığınızda, Veri Biliminin merkezine, yani **Pandas** kütüphanesine geçeceğiz. **Hazır olduğunuzda lütfen bildirin\!**

In [ ]:
import numpy as np
# Standart Python listesi
python_listesi = [1, 2, 3, 4, 5]

# NumPy Dizisi (Tek Boyutlu)
numpy_dizi = np.array(python_listesi)
print(numpy_dizi) # Çıktı: [1 2 3 4 5]

# Çok Boyutlu Dizi (Matris) Oluşturma (2x3)
matris = np.array([[10, 20, 30], [40, 50, 60]])
print(matris)
# Çıktı:
# [[10 20 30]
#  [40 50 60]]

In [ ]:
import numpy as np
dizi_a = np.array([1, 2, 3])
dizi_b = np.array([10, 20, 30])

# Vektörize Toplama (Eleman elemana toplama)
toplam = dizi_a + dizi_b
print(toplam) # Çıktı: [11 22 33]

# Skaler Çarpma (Her elemanı 2 ile çarp)
carpim = dizi_a * 2
print(carpim) # Çıktı: [2 4 6]

# Karşılaştırma (Boolean dizi döndürür)
buyuk_mu = dizi_a > 1
print(buyuk_mu) # Çıktı: [False  True  True]